INSERT INTO search_api (description, full_class_name, orders) VALUES ('카카오 API', 'com.kb.bookapp.business.component.kakaoApi.KakaoBookApiComponent', '2');
INSERT INTO search_api (description, full_class_name, orders) VALUES ('사용자 Repository', 'com.kb.bookapp.business.component.UserApi.UserBookApiComponent', '1');

INSERT INTO category VALUES ('PARENT', '1', '국내도서', '10000001', null);
INSERT INTO category VALUES ('PARENT', '2', 'e북', '10000002', null);
INSERT INTO category VALUES ('PARENT', '3', '영미도서', '10000003', null);
INSERT INTO category VALUES ('PARENT', '4', '일본도서', '10000004', null);
INSERT INTO category VALUES ('PARENT', '5', '프랑스도서', '10000005', null);
INSERT INTO category VALUES ('PARENT', '6', '독일도서', '10000006', null);
INSERT INTO category VALUES ('PARENT', '7', '스페인도서', '10000007', null);
INSERT INTO category VALUES ('PARENT', '8', '미분류', '10000008', null);

INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '시/에세이', '3', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '인문', '5', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '가정/생활', '7', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '요리', '8', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '건강', '9', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '취미/스포츠', '11', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '경제/경영', '13', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '자기계발', '15', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '정치/사회', '17', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '정부간행물', '18', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '역사/문화', '19', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '종교', '21', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '예술/대중문화', '23', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '중/고등학습', '25', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '기술/공학', '26', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '외국어', '27', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '과학', '29', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '취업/수험서', '31', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '여행/기행', '32', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '컴퓨터/IT', '33', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '잡지', '35', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '사전', '37', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '청소년', '38', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '초등참고서', '39', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '유아', '41', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '아동', '42', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '어린이영어', '45', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '만화', '47', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '대학교재', '50', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '어린이전집', '51', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '한국소개도서', '53', 1);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '소설', '901', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '장르소설', '902', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '시/에세이', '903', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '경제/경영', '904', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '자기계발', '905', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '인문', '906', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '정치/사회', '907', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '로맨스/무협/판타지', '908', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '종교', '909', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '예술/대중문화', '910', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '가정/생활', '911', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '건강', '912', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '여행/취미', '913', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '청소년', '914', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '학습/수험서', '915', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '유아', '916', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '아동', '917', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '외국어/사전', '918', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '과학', '919', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '컴퓨터/IT', '920', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '잡지', '921', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '만화', '922', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '외국도서', '923', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '무료eBook', '924', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '개인출판', '925', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '오디오북', '926', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '연재', '951', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', 'eReader Free', '953', 2);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '문학', '101', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '취미/실용/여행', '103', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '생활/요리/건강', '105', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '예술/건축', '107', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '인문/사회', '109', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '경제/경영', '111', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '과학/기술', '113', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '아동', '115', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '한국관련도서', '117', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', 'NON_BOOK', '119', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', 'UMI', '120', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', 'ELT/영어교재', '181', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '어린이영어', '183', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '대학교재', '191', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '중국관련도서', '194', 3);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '일서메인', '239', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '잡지', '241', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '엔터테인먼트', '243', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '만화', '245', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '문학', '247', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '라이트노벨', '249', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '문고(포켓북)', '251', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '신서(포켓북)', '253', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '아동', '255', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '실용서/예술', '257', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '인문/사회', '259', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '자연/기술과학', '261', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '어학/학습/사전', '263', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '문구/멀티/기타', '264', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '중국관련도서', '267', 4);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '프랑스종합', '486', 5);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '독일종합', '588', 6);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '스페인종합', '690', 7);
INSERT INTO category(category_type, name, sequence,parent_category_idx) VALUES ('CHILD', '미분류', '0', 8);

INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('1', '작사가1', '동해물과백두산이마르고닳도록1', '8', '9', '10', '5300', '카카오출판사', current_timestamp, '12312', '애국가 1절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('2', '작사가2', '하느님이보우하사우리나라만세1', '8', '9', '10', '12000', '카카오출판사', current_timestamp, '13441', '애국가 1절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('3', '작사가3', '무궁화삼처리화려강산1', '8', '9', '10', '15000', '카카오출판사', current_timestamp, '52353', '애국가 1절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('4', '작사가4', '대한사람대한으로길이보전하세1', '8', '9', '10', '6000', '카카오출판사', current_timestamp, '52342', '애국가 1절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('5', '작사가5', '남산위에저소나무철갑을두른듯2', '8', '9', '10', '12000', '카카오출판사', current_timestamp, '234235', '애국가 2절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('6', '작사가6', '바람서리불편함은우리기상일세2', '8', '9', '10', '500', '카카오출판사', current_timestamp, '234234', '애국가 2절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('7', '작사가7', '무궁화삼처리화려강산2', '8', '9', '10', '6000', '카카오출판사', current_timestamp, '5235235', '애국가 2절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('8', '작사가8', '대한사람대한으로길이보전하세2', '8', '9', '10', '400', '카카오출판사', current_timestamp, '23525', '애국가 2절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('9', '작사가9', '가을하늘공활한데높고구름없이3', '8', '9', '10', '44000', '카카오출판사', current_timestamp, '235235', '애국가 3절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('0', '작사가10', '밝은달은우리가슴일편단심일세3', '8', '9', '10', '32000', '카카오출판사', current_timestamp, '23423411', '애국가 3절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('10', '작사가11', '무궁화삼처리화려강산3', '8', '9', '10', '22000', '카카오출판사', current_timestamp, '6645', '애국가 3절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('11', '작사가12', '대한사람대한으로길이보전하세3', '8', '9', '10', '19000', '카카오출판사', current_timestamp, '334', '애국가 3절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('12', '작사가13', '이기상과이맘으로충성을다하여4', '8', '9', '10', '3000', '카카오출판사', current_timestamp, '734', '애국가 4절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('13', '작사가14', '괴로우나즐거우나나라사랑하세4', '8', '9', '10', '36000', '카카오출판사', current_timestamp, '3332', '애국가 4절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('14', '작사가15', '무궁화삼처리화려강산4', '8', '9', '10', '8000', '카카오출판사', current_timestamp, '234266', '애국가 4절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('15', '작사가16', '대한사람대한으로길이보전하세4', '8', '9', '10', '15200', '카카오출판사', current_timestamp, '63425', '애국가 4절', 2);

INSERT INTO member (password, username) VALUES ('$2a$10$xUDFpMbbjuBqtsZk0AoeFuvrCGCXasX2JCq0eNHQGfvn3POSUezAC', '김동훈2');