INSERT INTO search_api (description, full_class_name, orders) VALUES ('카카오 API', 'com.kb.bookapp.business.component.kakaoApi.KakaoBookApiComponent', '2');
INSERT INTO search_api (description, full_class_name, orders) VALUES ('사용자 Repository', 'com.kb.bookapp.business.component.UserApi.UserBookApiComponent', '1');

INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('1', '작사가1', '동해물과백두산이마르고닳도록1', '8', '9', '10', '5300', '카카오출판사', current_timestamp, '12312', '애국가 1절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('2', '작사가2', '하느님이보우하사우리나라만세1', '8', '9', '10', '12000', '카카오출판사', current_timestamp, '13441', '애국가 1절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('3', '작사가3', '무궁화삼처리화려강산1', '8', '9', '10', '15000', '카카오출판사', current_timestamp, '52353', '애국가 1절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('4', '작사가4', '대한사람대한으로길이보전하세1', '8', '9', '10', '6000', '카카오출판사', current_timestamp, '52342', '애국가 1절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('5', '작사가5', '남산위에저소나무철갑을두른듯2', '8', '9', '10', '12000', '카카오출판사', current_timestamp, '234235', '애국가 2절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('6', '작사가6', '바람서리불편함은우리기상일세2', '8', '9', '10', '500', '카카오출판사', current_timestamp, '234234', '애국가 2절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('7', '작사가7', '무궁화삼처리화려강산2', '8', '9', '10', '6000', '카카오출판사', current_timestamp, '5235235', '애국가 2절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('8', '작사가8', '대한사람대한으로길이보전하세2', '8', '9', '10', '400', '카카오출판사', current_timestamp, '23525', '애국가 2절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('9', '작사가9', '가을하늘공활한데높고구름없이3', '8', '9', '10', '44000', '카카오출판사', current_timestamp, '235235', '애국가 3절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('0', '작사가10', '밝은달은우리가슴일편단심일세3', '8', '9', '10', '32000', '카카오출판사', current_timestamp, '23423411', '애국가 3절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('10', '작사가11', '무궁화삼처리화려강산3', '8', '9', '10', '22000', '카카오출판사', current_timestamp, '6645', '애국가 3절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('11', '작사가12', '대한사람대한으로길이보전하세3', '8', '9', '10', '19000', '카카오출판사', current_timestamp, '334', '애국가 3절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('12', '작사가13', '이기상과이맘으로충성을다하여4', '8', '9', '10', '3000', '카카오출판사', current_timestamp, '734', '애국가 4절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('13', '작사가14', '괴로우나즐거우나나라사랑하세4', '8', '9', '10', '36000', '카카오출판사', current_timestamp, '3332', '애국가 4절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('14', '작사가15', '무궁화삼처리화려강산4', '8', '9', '10', '8000', '카카오출판사', current_timestamp, '234266', '애국가 4절', 2);
INSERT INTO user_book (accuracy, author, contents, isbn, keyword, overview, price, publisher, regi_datetime, sales, title, search_api_idx) VALUES ('15', '작사가16', '대한사람대한으로길이보전하세4', '8', '9', '10', '15200', '카카오출판사', current_timestamp, '63425', '애국가 4절', 2);

INSERT INTO member (password, username) VALUES ('$2a$10$xUDFpMbbjuBqtsZk0AoeFuvrCGCXasX2JCq0eNHQGfvn3POSUezAC', '김동훈2');